In [4]:
#Installing and Importing Libraries
!pip install tensorflow opencv-python tensorflow-hub matplotlib

import tensorflow as tf
import tensorflow_hub as hub
import cv2
from matplotlib import pyplot as plt
import numpy as np



In [5]:
#Setting the Memory for the GPU to avoid the OOM error
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
  tf.config.experimental.set_memory_growth(gpu, True)


In [6]:
#Importing the model from Tensorflow Hub
model = hub.load('https://tfhub.dev/google/movenet/multipose/lightning/1')
movenet = model.signatures['serving_default']

In [22]:
#Main function for the video capture.
cap = cv2.VideoCapture(0)
while cap.isOpened():
  ret, frame = cap.read()

  #resize the image and detect
  img = frame.copy()
  img = tf.image.resize_with_pad(tf.expand_dims(img, axis = 0), 352, 640)
  input_img = tf.cast(img, dtype = tf.int32)

  #detection section
  results = movenet(input_img)
  key_points_scores = results['output_0'].numpy()[:,:,:51].reshape(6,17,3)
  print(key_points_scores)

  #Render key points
  loop_through_people(frame, key_points_scores, EDGES, 0.3) 

  cv2.imshow('Movenet Multipose', frame)

  if cv2.waitKey(10) &  0xFF==ord('q'):
    break
cap.release()
cv2.destroyAllWindows()


[[[0.39915225 0.30927205 0.5804473 ]
  [0.37409678 0.30789512 0.6460492 ]
  [0.37574458 0.29439983 0.62269366]
  [0.37695011 0.29004255 0.3638915 ]
  [0.38103652 0.2487173  0.82238543]
  [0.53097725 0.3341671  0.7971926 ]
  [0.5235408  0.18721096 0.8661483 ]
  [0.71612257 0.34739384 0.7270977 ]
  [0.7224086  0.15011482 0.8412565 ]
  [0.8340548  0.34717032 0.48612824]
  [0.7383897  0.24152751 0.75232404]
  [0.9382698  0.31242257 0.5685276 ]
  [0.9372182  0.21644802 0.69008684]
  [0.9868519  0.37093514 0.04326958]
  [0.98279065 0.2235976  0.01839225]
  [0.98008794 0.26800457 0.00747579]
  [0.97947747 0.2594985  0.0031884 ]]

 [[0.4236436  0.7299331  0.6949898 ]
  [0.40315413 0.7449996  0.72351   ]
  [0.40173948 0.73110485 0.7481749 ]
  [0.41506514 0.78483504 0.7863485 ]
  [0.40935436 0.7438854  0.4432888 ]
  [0.5770744  0.84172744 0.7803291 ]
  [0.5686378  0.7100079  0.69663894]
  [0.7680687  0.85192674 0.7121887 ]
  [0.73855144 0.6831831  0.60520583]
  [0.9374116  0.8269911  0.69531906]

[[[0.4296989  0.7291997  0.5541986 ]
  [0.4067521  0.7436988  0.6466141 ]
  [0.4056199  0.7303409  0.78615767]
  [0.41943252 0.7838649  0.72974217]
  [0.41633898 0.7472865  0.46794084]
  [0.5803197  0.84113723 0.78760177]
  [0.57305264 0.709149   0.71981144]
  [0.7719087  0.8494218  0.6716581 ]
  [0.7450092  0.6840338  0.56856096]
  [0.93316966 0.8170614  0.48538327]
  [0.9146186  0.6770956  0.77757454]
  [0.9498899  0.8022791  0.6703544 ]
  [0.92836046 0.722053   0.72332495]
  [1.0163634  0.7894661  0.00447824]
  [0.9780239  0.6996972  0.12821078]
  [0.9775813  0.80385345 0.06170301]
  [0.9751436  0.7626215  0.03753478]]

 [[0.40001193 0.3110051  0.5325116 ]
  [0.37512815 0.3099227  0.6223468 ]
  [0.37679696 0.29576445 0.67215097]
  [0.3765496  0.29420668 0.30745593]
  [0.38112617 0.25062555 0.72460693]
  [0.5289742  0.33331886 0.7856205 ]
  [0.5261303  0.1880835  0.82599115]
  [0.705568   0.3534093  0.5850817 ]
  [0.72723454 0.1559235  0.8304539 ]
  [0.833347   0.355553   0.20749426]

[[[0.43809503 0.7270906  0.5763002 ]
  [0.41426083 0.7426032  0.6949672 ]
  [0.41488642 0.729086   0.7761067 ]
  [0.42857218 0.7826114  0.7128305 ]
  [0.42710721 0.74721706 0.42220324]
  [0.58773375 0.8417093  0.83429384]
  [0.5811411  0.70491314 0.6649829 ]
  [0.7827289  0.8454499  0.7204145 ]
  [0.7530921  0.68223184 0.57936776]
  [0.92742074 0.8041626  0.39268756]
  [0.9339195  0.6733081  0.5752004 ]
  [0.9493426  0.8078186  0.6784667 ]
  [0.9362296  0.72295916 0.7164269 ]
  [1.0136482  0.77755636 0.00947961]
  [0.98537153 0.70582724 0.12493839]
  [0.98334706 0.77657175 0.06074801]
  [0.96690154 0.7791824  0.03058497]]

 [[0.39668337 0.31443366 0.5812914 ]
  [0.3727344  0.31490073 0.7480371 ]
  [0.37355947 0.29971436 0.6580048 ]
  [0.37365967 0.29697108 0.365392  ]
  [0.37672648 0.25335452 0.72397953]
  [0.5276027  0.33983633 0.764249  ]
  [0.53075135 0.19361667 0.82549894]
  [0.7040383  0.35537997 0.58770514]
  [0.7323051  0.16289406 0.8458012 ]
  [0.83706284 0.35458457 0.5399891 ]

[[[0.44692415 0.7231217  0.6470055 ]
  [0.42581698 0.73778594 0.68721795]
  [0.42277017 0.72744465 0.58237153]
  [0.44191206 0.77916306 0.7301346 ]
  [0.43694282 0.7477796  0.34516686]
  [0.59092504 0.84121245 0.8014312 ]
  [0.58335257 0.700136   0.77179974]
  [0.7895696  0.83938164 0.6536892 ]
  [0.7653065  0.68106955 0.7074547 ]
  [0.944      0.7978366  0.38728863]
  [0.951069   0.6664257  0.5078133 ]
  [0.9417781  0.8041221  0.67575485]
  [0.92334795 0.7217409  0.69300264]
  [1.0143905  0.78289527 0.01007165]
  [0.9913913  0.7051913  0.09390744]
  [0.97855777 0.7789117  0.10552762]
  [0.9660082  0.7873289  0.0465322 ]]

 [[0.4185215  0.5052322  0.38008028]
  [0.39696482 0.51852864 0.39943975]
  [0.39549866 0.5042051  0.6874887 ]
  [0.41143167 0.55847925 0.5838642 ]
  [0.40664172 0.51552075 0.44137043]
  [0.5789024  0.6001776  0.5046623 ]
  [0.56799215 0.47874996 0.7423058 ]
  [0.7662836  0.6297801  0.3075008 ]
  [0.7458488  0.45285416 0.5604741 ]
  [0.8732969  0.5938117  0.26103482]

[[[0.44972825 0.7210132  0.5795825 ]
  [0.42603558 0.73490614 0.61688614]
  [0.42447153 0.72441894 0.6294015 ]
  [0.43879032 0.7753953  0.7029794 ]
  [0.43770072 0.7451367  0.30920783]
  [0.58814263 0.8390083  0.8057274 ]
  [0.58127004 0.6966173  0.812372  ]
  [0.7939233  0.83546925 0.5831559 ]
  [0.7724971  0.6783804  0.6924967 ]
  [0.96804905 0.8002265  0.3385522 ]
  [0.94898254 0.6639499  0.60898197]
  [0.9652513  0.8044982  0.72706884]
  [0.94684654 0.7216381  0.677499  ]
  [1.017965   0.7821688  0.01262797]
  [0.98082113 0.66831475 0.14481702]
  [0.9779582  0.7544874  0.20982452]
  [0.9689778  0.8007623  0.05959544]]

 [[0.39664894 0.31148916 0.5760912 ]
  [0.37362036 0.31585813 0.71117747]
  [0.37099618 0.29681572 0.8387657 ]
  [0.37457702 0.30823773 0.45830148]
  [0.36806402 0.25275218 0.7037413 ]
  [0.507061   0.34883782 0.7776907 ]
  [0.52913    0.20032182 0.8318181 ]
  [0.7138121  0.37746817 0.606534  ]
  [0.73768824 0.16995202 0.8304786 ]
  [0.65745187 0.3725307  0.17334977]

[[[0.43187475 0.5214113  0.3615337 ]
  [0.4094759  0.5336587  0.38290516]
  [0.4099936  0.5214816  0.49363756]
  [0.42584997 0.57288164 0.45019633]
  [0.42305207 0.53738326 0.32458237]
  [0.60422873 0.62931967 0.76598847]
  [0.58016026 0.48962554 0.7231091 ]
  [0.7728628  0.6276693  0.5998343 ]
  [0.7604882  0.46139988 0.6004927 ]
  [0.88941073 0.6225302  0.3860392 ]
  [0.87247217 0.50302887 0.5478246 ]
  [0.95274657 0.59426326 0.5810745 ]
  [0.92070836 0.51240337 0.46493486]
  [0.9794545  0.5894875  0.1415717 ]
  [0.92709464 0.50872076 0.04007325]
  [0.9482787  0.5921921  0.10865843]
  [0.90372175 0.50661355 0.09571394]]

 [[0.39101207 0.31419072 0.7387674 ]
  [0.3702374  0.31862915 0.7086884 ]
  [0.3637929  0.29924503 0.6579492 ]
  [0.37290904 0.3099409  0.46749038]
  [0.35750088 0.2538698  0.6984373 ]
  [0.4997886  0.3501035  0.709513  ]
  [0.5295638  0.20045435 0.7921    ]
  [0.702992   0.39100552 0.6990231 ]
  [0.73965055 0.17505851 0.78262764]
  [0.6324103  0.37664565 0.15200038]

[[[0.43166283 0.5371625  0.33808607]
  [0.40970063 0.5519474  0.49918237]
  [0.40952918 0.5347374  0.68781567]
  [0.43656662 0.58921707 0.5588579 ]
  [0.4217365  0.54109186 0.3896933 ]
  [0.61522776 0.63953024 0.6935032 ]
  [0.5781043  0.4982619  0.8006079 ]
  [0.7770631  0.62848645 0.43061167]
  [0.74500304 0.46197185 0.5241026 ]
  [0.9153613  0.6171681  0.26357892]
  [0.86547947 0.49619874 0.5328568 ]
  [0.95899767 0.5909237  0.60488015]
  [0.93044853 0.510313   0.529834  ]
  [0.966644   0.6105675  0.03695076]
  [0.92761874 0.49782854 0.02845897]
  [0.93614876 0.6124763  0.05531278]
  [0.9016652  0.503931   0.02832957]]

 [[0.38731533 0.31765503 0.6684728 ]
  [0.36805275 0.32008147 0.8290733 ]
  [0.362995   0.3021473  0.67858434]
  [0.36885908 0.31088188 0.4725553 ]
  [0.36071554 0.255775   0.64094955]
  [0.49719122 0.3483533  0.73454374]
  [0.53508765 0.20094423 0.73999727]
  [0.6916101  0.40433908 0.66489846]
  [0.7444356  0.18203776 0.81482583]
  [0.64973587 0.3755438  0.18469033]

  [0.67475325 0.01535396 0.0663038 ]]]
[[[0.42889163 0.54583895 0.38833532]
  [0.4094955  0.5595121  0.45292196]
  [0.40588444 0.5445574  0.6833505 ]
  [0.42971963 0.5986012  0.5084584 ]
  [0.4184078  0.5543806  0.38683978]
  [0.61059713 0.64507693 0.7818345 ]
  [0.57081634 0.5006387  0.7498983 ]
  [0.7837803  0.6374358  0.66923064]
  [0.73487663 0.46518132 0.5416853 ]
  [0.9290601  0.6118496  0.36894134]
  [0.8527816  0.48667955 0.6746991 ]
  [0.96018255 0.59892315 0.7578566 ]
  [0.9497241  0.5104159  0.63928556]
  [0.97999394 0.6265755  0.02288723]
  [0.9777992  0.49459338 0.02794416]
  [0.9834407  0.58472866 0.04160522]
  [0.96615285 0.54877895 0.03346895]]

 [[0.39387408 0.31939095 0.62183374]
  [0.3727289  0.3204833  0.7452628 ]
  [0.37222546 0.30344638 0.7924131 ]
  [0.37568626 0.30970928 0.3606078 ]
  [0.37659654 0.2578385  0.62138706]
  [0.50656873 0.34850916 0.7131501 ]
  [0.54262114 0.20462683 0.74382323]
  [0.6820177  0.40470156 0.23779155]
  [0.75441265 0.19432218 0.8072652

[[[0.39892107 0.31945    0.61378944]
  [0.37877306 0.3209141  0.84220475]
  [0.37698838 0.30301526 0.74256027]
  [0.38348767 0.3072523  0.44328916]
  [0.38633642 0.25664553 0.6697375 ]
  [0.5094415  0.3502261  0.817057  ]
  [0.5456435  0.20677395 0.8096729 ]
  [0.67868805 0.41141436 0.42658043]
  [0.76449585 0.19769436 0.8303565 ]
  [0.7046497  0.39433786 0.2931834 ]
  [0.7519531  0.28728855 0.51849395]
  [0.9321265  0.33243927 0.23091115]
  [0.9308498  0.24898708 0.5231707 ]
  [0.9695894  0.39801455 0.16217214]
  [0.96777284 0.26067832 0.06091641]
  [0.9695037  0.33851495 0.11801913]
  [0.9588256  0.2874231  0.07965972]]

 [[0.4241737  0.55094784 0.45299453]
  [0.40359455 0.56651604 0.61299866]
  [0.4008379  0.54946226 0.82533246]
  [0.4258908  0.6036152  0.7126678 ]
  [0.41527337 0.55848706 0.34610683]
  [0.6033902  0.6460411  0.7424483 ]
  [0.56078345 0.5063674  0.75810796]
  [0.7744565  0.6453745  0.72641504]
  [0.7198615  0.4663461  0.6212115 ]
  [0.9180971  0.61146057 0.6829717 ]

[[[0.40324345 0.323276   0.7084545 ]
  [0.3807741  0.32301337 0.70136034]
  [0.38036317 0.30654383 0.7473514 ]
  [0.38843268 0.30786422 0.40269637]
  [0.39318886 0.26176336 0.7892694 ]
  [0.5157666  0.35469174 0.7696539 ]
  [0.5552987  0.20801559 0.74704164]
  [0.6846449  0.41386423 0.39917594]
  [0.7706001  0.19641386 0.8692169 ]
  [0.73750925 0.38665828 0.22138244]
  [0.74923086 0.28856352 0.5126781 ]
  [0.9252186  0.33570498 0.29938114]
  [0.920637   0.2494132  0.6223034 ]
  [0.963733   0.3937441  0.10657874]
  [0.9639651  0.23398864 0.03392257]
  [0.9746402  0.3427969  0.17160684]
  [0.9665321  0.3017109  0.06511609]]

 [[0.41277128 0.55424905 0.5530646 ]
  [0.39261377 0.56949294 0.65473807]
  [0.392554   0.5523266  0.66160303]
  [0.40933824 0.6055343  0.5782787 ]
  [0.40369833 0.55980504 0.35912913]
  [0.5908684  0.64674723 0.7325732 ]
  [0.5498957  0.5102605  0.71352804]
  [0.7684884  0.6564937  0.6617685 ]
  [0.7141995  0.47039452 0.5174401 ]
  [0.9030622  0.6034066  0.32935408]

[[[0.39748812 0.55358124 0.498753  ]
  [0.37781167 0.5681171  0.65766793]
  [0.37790427 0.5513183  0.6874282 ]
  [0.39545074 0.6058704  0.5835741 ]
  [0.39037073 0.55873895 0.37437525]
  [0.5709216  0.65153766 0.78665125]
  [0.545041   0.51483625 0.8200048 ]
  [0.7524961  0.660563   0.7697633 ]
  [0.7004916  0.4730321  0.61771595]
  [0.8607414  0.59330785 0.35136718]
  [0.77988183 0.46479574 0.5503728 ]
  [0.9258865  0.63230795 0.42086723]
  [0.912499   0.5448821  0.5182335 ]
  [0.98503876 0.6503996  0.0692305 ]
  [0.96248144 0.49686632 0.14112212]
  [0.9579147  0.61485195 0.04082952]
  [0.9625659  0.5643449  0.03304916]]

 [[0.40704298 0.32475403 0.57649344]
  [0.38476503 0.32547173 0.7370775 ]
  [0.3835081  0.308467   0.68899035]
  [0.39118433 0.31037897 0.44573352]
  [0.3991232  0.2636652  0.68721044]
  [0.5213032  0.3561339  0.8045304 ]
  [0.55510455 0.21143615 0.75443035]
  [0.670732   0.40682608 0.4491021 ]
  [0.76309603 0.19596748 0.7693565 ]
  [0.7475458  0.41529855 0.15570216]

  [0.67499924 0.02134108 0.07320198]]]
[[[0.40302542 0.32596624 0.6660435 ]
  [0.38078126 0.3272389  0.77664924]
  [0.3799938  0.30911642 0.76783013]
  [0.38705033 0.3145144  0.4125486 ]
  [0.39396587 0.2646806  0.8067901 ]
  [0.5226227  0.3581011  0.7876385 ]
  [0.55468655 0.21059728 0.7622076 ]
  [0.68606204 0.40661964 0.31395096]
  [0.7713914  0.19257464 0.7686708 ]
  [0.7355981  0.41070077 0.13609506]
  [0.73698825 0.277132   0.72501796]
  [0.9279397  0.34335986 0.5924002 ]
  [0.9383474  0.24885531 0.74957955]
  [0.96646094 0.40468428 0.14474055]
  [0.9827997  0.24271278 0.04008226]
  [0.96987355 0.33031464 0.09766243]
  [0.9639188  0.31689072 0.04000687]]

 [[0.39832684 0.55159175 0.47590125]
  [0.37721345 0.5664767  0.6068047 ]
  [0.37894455 0.54866856 0.8379558 ]
  [0.3903648  0.60426927 0.64771265]
  [0.3894733  0.5535672  0.42562085]
  [0.5588337  0.65012926 0.87692547]
  [0.5490036  0.5139822  0.78941613]
  [0.7457462  0.66469735 0.5590173 ]
  [0.7081869  0.4777727  0.3891639

[[[0.40050888 0.32766184 0.71327055]
  [0.37853065 0.32913437 0.8753888 ]
  [0.37743682 0.31029916 0.75663215]
  [0.38552073 0.31739065 0.39776522]
  [0.39263043 0.264865   0.83413726]
  [0.53092    0.36156175 0.7741663 ]
  [0.55321264 0.21105182 0.7959894 ]
  [0.67581457 0.40007326 0.23895213]
  [0.77323145 0.19012761 0.8293447 ]
  [0.73516005 0.4151372  0.20625857]
  [0.7291681  0.2768192  0.79368263]
  [0.9504129  0.34354854 0.61979663]
  [0.9497045  0.24906316 0.7407714 ]
  [0.9555758  0.40681586 0.15844573]
  [0.98193425 0.24149556 0.04320305]
  [0.97197264 0.32240823 0.02356422]
  [0.9747756  0.31868532 0.01713347]]

 [[0.40882003 0.7339421  0.47717398]
  [0.38481787 0.74963903 0.50648046]
  [0.38382202 0.7327617  0.6958239 ]
  [0.40084267 0.79224676 0.8224023 ]
  [0.39494875 0.74566525 0.43828818]
  [0.5550013  0.84865123 0.8646689 ]
  [0.53958684 0.7112199  0.8048144 ]
  [0.76048964 0.8804477  0.73211366]
  [0.7272983  0.6894446  0.5303364 ]
  [0.9408555  0.908946   0.65388346]

[[[0.3989571  0.32947144 0.6672964 ]
  [0.37370992 0.32998693 0.70852447]
  [0.37440842 0.31092036 0.6790767 ]
  [0.37874076 0.31803104 0.3811003 ]
  [0.3890288  0.2661905  0.7606172 ]
  [0.5317343  0.36650464 0.76557267]
  [0.54557043 0.21284166 0.77210355]
  [0.72962    0.391921   0.3932369 ]
  [0.77423775 0.18981773 0.81992453]
  [0.701878   0.40105054 0.20200115]
  [0.7281978  0.27251717 0.7852869 ]
  [0.93614453 0.34242326 0.58843553]
  [0.94798565 0.2514139  0.6345128 ]
  [0.98185974 0.40618214 0.14140739]
  [0.98355156 0.2336226  0.04190318]
  [0.9654894  0.30994454 0.05467049]
  [0.9594439  0.31775963 0.05068066]]

 [[0.42242533 0.5570208  0.5878412 ]
  [0.39553535 0.57222384 0.65226734]
  [0.3992184  0.5456547  0.8123798 ]
  [0.4041867  0.5985903  0.5365565 ]
  [0.4094727  0.5377046  0.60638046]
  [0.56763935 0.6444759  0.71087253]
  [0.572347   0.5050826  0.79043317]
  [0.748158   0.6593587  0.29416096]
  [0.75493574 0.47969365 0.21237792]
  [0.85141194 0.59357274 0.7472723 ]

[[[0.38910946 0.33130032 0.640843  ]
  [0.36821964 0.3326731  0.79661095]
  [0.36942682 0.31292424 0.6857585 ]
  [0.3735873  0.3232695  0.39681345]
  [0.38334966 0.26766402 0.7288312 ]
  [0.52206063 0.36641464 0.788063  ]
  [0.5380722  0.2167069  0.79687643]
  [0.7334797  0.3869455  0.561482  ]
  [0.7647252  0.19161296 0.798561  ]
  [0.69169647 0.40348268 0.08351007]
  [0.7229584  0.27261677 0.760276  ]
  [0.90637887 0.34314466 0.25324473]
  [0.91387594 0.25461668 0.436637  ]
  [0.9733606  0.41290933 0.09901816]
  [0.9734478  0.27209744 0.03980151]
  [0.9730681  0.34442818 0.05505425]
  [0.9660606  0.29437083 0.04480349]]

 [[0.4360764  0.5566389  0.6530331 ]
  [0.40705642 0.56943214 0.6924672 ]
  [0.4106366  0.5420782  0.64358395]
  [0.40974116 0.589333   0.59563595]
  [0.41717762 0.5282842  0.7358674 ]
  [0.5713478  0.6365933  0.6495736 ]
  [0.5846408  0.49920556 0.73392785]
  [0.7520359  0.6504368  0.65403473]
  [0.7262332  0.48275253 0.37010205]
  [0.85384625 0.59849423 0.690801  ]

In [16]:
# Function to loop through the people
def loop_through_people(frame, key_points_scores, edges, confidence_threshold):
    for person in key_points_scores:
        draw_connections(frame, person, edges, confidence_threshold)
        draw_keypoints(frame, person, confidence_threshold)

In [18]:
#unction to draw the key points 

def draw_keypoints(frame, keypoints , confidence_threshold):
    y,x,c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf>confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)),4, (0,255,0), -1)

In [11]:
#Edges betweent the keypoints
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [12]:

def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 4)